window.SUBSTACK_NOTES = [
  {
    "id": 218467499,
    "date": "2026-02-23T11:41:27.586Z",
    "body": "Cuidado em achar que não é doomscrolling só porque a entidade mudou de nome.\n\nSubstack ainda é “rede social”.",
    "likes": 1,
    "replies": 1,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-218467499",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 217740831,
    "date": "2026-02-21T17:51:09.132Z",
    "body": "Comecei a escrever por puro ódio ao Zeitgeist que sou obrigado a viver. Todo santo dia, sento e digito pra apaziguar essa revolta. \n\nQueria escrever esperanças, só que, por me inspirar na realidade, tudo acaba naturalmente em distopia, sátira e realismo imundo --- ou viram esses Lauros ai.",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-217740831",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 217664105,
    "date": "2026-02-21T14:53:54.227Z",
    "body": "Vou guardar porque isso ai tem coisa",
    "likes": 2,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-217664105",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 217115519,
    "date": "2026-02-20T10:21:19.934Z",
    "body": "Sei que pra crescer tenho que me render a criar um monte de note clichê, com imagem, com tirinhas, com sacadas e blábláblá. Me recuso.",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-217115519",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 217106055,
    "date": "2026-02-20T09:32:14.104Z",
    "body": "Essa coisa, meio homem e meio nada.",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-217106055",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 216754153,
    "date": "2026-02-19T16:12:24.151Z",
    "body": "Da série “sugestões de correções do Google Docs”.\n\nQue isso, cara? 😮",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-216754153",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 205801244,
    "date": "2026-01-27T07:47:42.444Z",
    "body": "Palavra de IA: visceral. \n\n\n\nNinguém dizia isso, dizia?",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-205801244",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 167074203,
    "date": "2025-10-16T19:53:42.848Z",
    "body": "Palácio do Marquês de Pombal.\n\nQuase secreto!\n\nNenhum zumbi com celular na mão.\n\nSempre aberto e sempre sem ninguém.\n\nPerfeito.",
    "likes": 0,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-167074203",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 165232086,
    "date": "2025-10-11T10:13:51.691Z",
    "body": "Hoje, o Google Docs, me sugeriu corrigir “dormindo” para “durmindo”. Talvez a IA não seja assim tão perigosa, só é excelente em vestir máscaras; mas toda máscara acaba caindo de vez em quando.",
    "likes": 1,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-165232086",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 159124726,
    "date": "2025-09-23T17:37:45.257Z",
    "body": "Uma manhã ordinária,\n\nde cor ofuscada.\n\nMeu bocejo calado,\n\nculpado e frustrado.\n\nPobre alma cansada\n\ne se sente tão rasa.\n\nAlarme é trabalho,\n\nacorda operário.\n\nMesmo na alvorada,\n\nrotina apressada.\n\nCafé feito rápido\n\njá nem sinto se faço.\n\nSempre olhos fechados,\n\nsempre robotizado.\n\nHá vontade sem chama,\n\nsou um mero programa.\n\nMaldito raio de sol!\n\nme cega e acorda.\n\nÉs Lindo Raio de Sol!\n\nÉs como uma corda.\n\nJogas pra mim,\n\nSem sucumbir,\n\nconsigo sair.\n\nOuço de ti,\n\nVive o presente,\n\nsê consciente.",
    "likes": 2,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-159124726",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 158287185,
    "date": "2025-09-21T10:09:52.666Z",
    "body": "Não sei se amo ou odeio essa plataforma. Por um lado, é bom: conteúdo de qualidade sem ter que curar por dias e protege o que publicamos. Por outro lado: não há como editar/ver seus rascunhos pelo app mobile, não há opção de filtros, não há como ver só coisas em português, o algoritmo parece demorar muito para entender que eu NÃO QUERO LER BABOSEIRA DE COACH e o meu nêmesis do momento que é:  não há como FORÇAR A FORMATAÇÃO, que é absolutamente necessário em poesia concreta do vanguardismo, eu mesmo não consigo postar o meu texto sem ficar extremamente frustrado quando abro. A FORMA COMO AS PALAVRAS ESTÃO DISPOSTAS IMPORTA, SUBSTACK! Esse editor de texto daqui É HORRÍVEL.",
    "likes": 3,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-158287185",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  },
  {
    "id": 158104815,
    "date": "2025-09-20T18:11:49.980Z",
    "body": "título: A raiz. (Instagram)\n\n      F\n\n           O               \n\nFOfoquinha quando nasce se esparrama pelo chão.\n\nNão sei o que coloco aqui pra chamar sua atenção\n\nAquela música do momento pra ganhar aprovação?\n\n                     D\n\n                          A\n\nDAnço com o carro em movimento ofendendo o firmamento?\n\nPosso esquecer de quem eu sou e imitar algum ator?\n\nNarciso afogou bonito, mas o que isso tem a ver comigo?\n\nVai uma legenda sem contexto ou um excerto de louvor?\n\n                                        S\n\n                                             E\n\nSE for texto de Jesus, Kardec e Buda, você curte a minha bunda?\n\nMeto a moda que dá like, roubei, comprei o nike\n\nTrabalhei perdi meu life e comprei o Balcor Retard\n\nJá sei! Vou ostentar meu mômô: um mecômio verdadeiro!\n\nBato a foto e meto o peito! Depois procuro algum defeito: justifico um chifre feito! \n\nNa verdade, decidi um sacramento.\n\nDesculpe o tormento pois vou usar o bom momento, pra bancar o seu avô:\n\n                           \"Olha pra essa merda,\n\n                                 tá geral igual robô!\n\n                                 Pega ai a sua bike,\n\n                             Mete o pé desse côcô!\n\n                         Vai preservar sua sanidade\n\n                   Pra ser independente de doutor.\n\n                      É depressão na humanidade\n\n                             É Rivotril, é Prozanac.\n\n                                 É vitrine de amor.\n\n                         Prezo pela individualidade\n\n                                Pela autenticidade.\n\n                             À contemporaneidade,\n\n                             minha alma eu não dou.\"\n\nDeclaro \n\nfuga \n\nao \n\nmanicomio\n\n                                                         \n\nE \n\nÉ   \n\nP R A    longe                                                                                 que eu vou.\n\nPoema de quando eu era mais cru (2014).\n\nTítulo: A raíz.",
    "likes": 1,
    "replies": 0,
    "restacks": 0,
    "url": "https://substack.com/@pixwx/note/c-158104815",
    "user_photo": "https://substack-post-media.s3.amazonaws.com/public/images/913aa8e4-fb4b-48ea-9817-c459b950781c_1024x1024.png",
    "user_name": "Gabriel A. A. de A.",
    "user_handle": "pixwx"
  }
];
if(typeof window.renderSubstackNotes === 'function') window.renderSubstackNotes();